### ISSUE TITLE
Alignment of bi0s logo not in centre when opened in Mobile browser. 

### ISSUE THREAD

**Issue by g0kkk** [teambi0s/teambi0s.github.io#16]

**Comment by nightrainlily** [comment]
i'll try to work on this.

**Comment by deepankarmalhan** [comment]
I just tested out the site, and it seems that it is in the middle. The container class for Bootstrap takes care of horizontal alignment for mobile. Please let me know if there is a way to recreate the issue because I can't recreate it as of now.

**Comment by g0kkk** [comment]
@nightrainlily sure. 
@deepankarmalhan for a few phones that we had tested, the logo was being aligned towards the left.
