### ISSUE TITLE
Update the README file

### ISSUE THREAD

**Issue by g0kkk** [teambi0s/teambi0s.github.io#17]

**Comment by michelvosje** [comment]
Let me look into this. Any specific things before pushing?

**Comment by rsm23** [comment]
Please check #20 #19

**Comment by rsm23** [comment]
please give it a label of hacktoberfest

**Comment by michelvosje** [comment]
How is the reame.md suddenly updated?

**Comment by michelvosje** [comment]
Nice. Plz post comments about merging before wasting other people their time. jezus....
