### ISSUE TITLE
Modify the font colour for team members list

### ISSUE THREAD

**Issue by g0kkk** [teambi0s/teambi0s.github.io#18]

**Comment by scarabcoder** [comment]
May I work on this, or have you already assigned someone?

**Comment by g0kkk** [comment]
@scarabcoder you can work on it

**Comment by scarabcoder** [comment]
Great, thanks!

**Comment by scarabcoder** [comment]
@gokulkrishna01 Do the changes need to be made at http://bi0s.in/#team or the list above it?

**Comment by g0kkk** [comment]
@scarabcoder The list above it
