### ISSUE TITLE
Embed Twitter timeline to the website.

### ISSUE THREAD

**Issue by g0kkk** [teambi0s/teambi0s.github.io#21]

**Comment by Dheeraj1998** [comment]
At which location do you want to add the twitter timeline?

**Comment by g0kkk** [comment]
@Dheeraj1998 right below `Contact us` section

**Comment by g0kkk** [comment]
@Dheeraj1998 from here - https://twitter.com/teambi0s

**Comment by Dheeraj1998** [comment]
Okay, will start working on it.

**Comment by g0kkk** [comment]
@Dheeraj1998 did you test it for both mobile and desktop version?

**Comment by Dheeraj1998** [comment]
@gokulkrishna01  Yeah, the tweet section has been tested on the mobile version also. The tweet section is being shown two times due to the two different PRs with the same function being pushed.
